em++ Envari\source\Scripting\LUAScriptingBindings.cpp ^
    -I ..\..\Envari\LUA\include ^
    -I ..\..\Envari\source\Defines ^
    -I ..\..\Envari\source\Engine ^
    -I ..\..\Envari\STB ^
    -I ..\..\Envari\Miniaudio ^
    -I ..\..\Envari\Engine ^
    -O2 ^
    -DLUA_ENABLED=1 ^
    -DPLATFORM_WASM=1 ^
    -DPLATFORM_EDITOR=1 ^
    -s FORCE_FILESYSTEM=1 ^
    -s USE_SDL=2 ^
    -std=c++17 ^
    -c ^
    -o build\editorhtml5\LUAScriptingBindings.o ^ 
    --no-heap-copy