#ifndef EDITOR_DEFINES_H
#define EDITOR_DEFINES_H

#define BUFFER_CHANNEL_TO_SHOW_SIZE SOUND_SAMPLE_RATE * 1
#define BUFFER_TO_SHOW_SIZE BUFFER_CHANNEL_TO_SHOW_SIZE * SOUND_CHANNELS

#define TIME_BUFFER_SIZE 1000

#define CONSOLE_HISTORY_SIZE 25
#define CONSOLE_HISTORY_SAVE_SIZE 25

#endif