#ifndef RENDER_DEFINES_H
#define RENDER_DEFINES_H

#define TRANSFORM_STACK_SIZE 16

#define LUA_FILENAME_MAX 256

#define SHADER_FILENAME_MAX 256

#define SPECIAL_ASCII_CHAR_OFFSET 32
#define FONT_CHAR_SIZE 512

#define SOURCE_TYPE const char* const

#ifndef DEFAULT_WRAP_S
#define DEFAULT_WRAP_S GL_CLAMP_TO_EDGE
#endif
#ifndef DEFAULT_WRAP_T
#define DEFAULT_WRAP_T GL_CLAMP_TO_EDGE
#endif

#ifndef DEFAULT_MIN_FILTER
#define DEFAULT_MIN_FILTER GL_LINEAR_MIPMAP_LINEAR
#endif
#ifndef DEFAULT_MAG_FILTER
#define DEFAULT_MAG_FILTER GL_LINEAR_MIPMAP_LINEAR
#endif

#ifndef FRAMEBUFFER_DEFAULT_FILTER
#define FRAMEBUFFER_DEFAULT_FILTER GL_LINEAR
#endif

#define DEFAULT_FONT_ATLAS_WIDTH 1024
#define DEFAULT_FONT_ATLAS_HEIGHT 1024

#endif