#ifndef EDITORWINDOWSCONFIGMAP_H
#define EDITORWINDOWSCONFIGMAP_H

const char* EDITORWINDOWSCONFIG_INITLUASCRIPT = "initLuaScript";
const char* EDITORWINDOWSCONFIG_WINDOWSIZE = "windowSize";
const char* EDITORWINDOWSCONFIG_BUFFERSIZE = "bufferSize";
const char* EDITORWINDOWSCONFIG_RENDERSCALE = "renderScale";
const char* EDITORWINDOWSCONFIG_WINDOWTITLE = "windowTitle";
const char* EDITORWINDOWSCONFIG_VSYNC = "vsync";
const char* EDITORWINDOWSCONFIG_FPSLIMIT = "fpsLimit";
const char* EDITORWINDOWSCONFIG_FPSFIXED = "fpsFixed";

#endif